version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
