name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Set image and tag variables
        id: vars
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/mi-app
          TAG=latest
          SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "image_name=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag_latest=${TAG}" >> $GITHUB_OUTPUT
          echo "tag_sha=${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.tag_latest }} \
                       -t ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.tag_sha }} \
                       ./app

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.tag_latest }}
          docker push ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.tag_sha }}
